graph LR
    Python --> Streamlit
    Streamlit --> InterfaceWeb
    Python --> Pandas
    Python --> Plotly
    GitHub --> CI_CD
    CI_CD --> Testes
    CI_CD --> Deploy
    Deploy --> StreamlitCloud